### ISSUE TITLE
Project Goals

### ISSUE THREAD

**Issue by connorkuehl** [connorkuehl/llvm-project#1]
This is lifted from our requirements document. Since the "issues" portion of our project gets the most traffic from us, it's easier to keep these goals in our line of sight to stay focused.

- [ ] All structures marked with "__randomize_layout" have their field positions randomized, including bit fields. Relevant issues: #62 #98 #99 

- [ ] Reproducible random number (same seed needs to be saved as part of the build). Relevant issues: #55 

- [ ] Regression tests. Relevant issues: #84 

- [x] Publish this, regardless of upstream acceptance. Relevant issues: This one! :grinning: 

**If everything above has been checked off, then we have our minimum viable product!**

Stretch goals:

- [ ] Performance sensitive: Best-effort limit randomization to cache-line (64 byte) size regions, keep adjacent bit-fields together. Relevant issues: #83 

- [ ] Automatic Structure Selection: Find structures that should be automatically selected (for example, structures of entirely function pointers), disabled with "__no_randomize_layout". Relevant issues: #96 #97
